DROP DATABASE IF EXISTS user_db;
DROP DATABASE IF EXISTS item_db;
DROP DATABASE IF EXISTS delivery_db;
DROP DATABASE IF EXISTS payment_db;

CREATE DATABASE user_db;
CREATE DATABASE item_db;
CREATE DATABASE delivery_db;
CREATE DATABASE payment_db;