server:
  port:
    7001

spring:
  application:
    name:
      email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ucscgroupproject@gmail.com
    password: agoevsqmwavogsgv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true