server:
  port:
    8080

spring:
  application:
    name:
      api-gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/user/**
        - id: item
          uri: lb://ITEM
          predicates:
            - Path=/api/item/**
        - id: delivery
          uri: lb://DELIVERY
          predicates:
            - Path=/api/delivery/**
        - id: delivery
          uri: lb://DELIVERY
          predicates:
            - Path=/api/delivery/**
        - id: email
          uri: lb://EMAIL
          predicates:
            - Path=/api/email/**
        - id: sms
          uri: lb://SMS
          predicates:
            - Path=/api/sms/**
        - id: payment
          uri: lb://PAYMENT
          predicates:
            - Path=/api/payment/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true