server:
  port:
    7002

spring:
  application:
    name:
      sms
  datasource:
    url: jdbc:mysql://mysql:3307/emptum_sms_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true