apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptum
  labels:
    app: emptum
spec:
  replicas: 1
  template:
    metadata:
      name: emptum
      labels:
        app: emptum
    spec:
      containers:
        - name: emptum
          image: dhanushka117/emptum:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
      restartPolicy: Always
  selector:
    matchLabels:
      app: emptum
