server:
  port:
    6001

spring:
  application:
    name:
      user
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/user_db
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
#  datasource:
##    url: jdbc:mysql://localhost:3306/csp_user_db
#    url: jdbc:mysql://localhost:3307/emptum_user_db
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL57Dialect
#      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true